### PR TITLE
added react project plan

### PR DESCRIPTION
**Pull request by mikef80**

### CODE REVIEW

**Comment by nc-modou** [comment]
Looks good for the most part!

However, the wireframe on the first page is confusing - how can you have an element that is either an article or a topic? Where would you click to pick the topics? Would you use the same element to display articles as you would use to display possible topics? This needs a bit of reconsideration

Also, some mention of the URL on the component tree would be great, as it's not super clear what component matches to which wireframe atm - especially with the topics/articles page.

**Comment by mikef80** [comment]
I've made amendments and made a new commit with the updated project plan

**Comment by ghost** [comment]
Looks much better, have at it!

**Comment by mikef80** [comment]
awesome - thank you!

**Pull request merged**
